#	
#	file : Makefile
#	description:
#
#

##	system target
.PHONY: main install all_modules

main: all_modules

ALL_TASK:=$(call SET_GetValSet, $(SET_Task))
all_modules: $(ALL_TASK)

install:
	@echo "no support for this now !"
