PROJECT_OUT            :=$(PROJECT_TOP_DIR)/out
PROJECT_VERSION        :=1.1.1
PROJECT_BUILD_ID       :=1234
PROJECT_BUILD_TYPE     :=debug
PROJECT_COMPANY        :=TuoAn
PROJECT_MODULE_OWNER   :=hello

CROSS_COMPILE          :=
